<div id="BBox" class="alert alert-success" style="font-family:courier;color:black;">
        <h1>Executing SQL Queries with Python - Student Registration System</h1>
        <p>This tutorial demonstrates how to interact with a MySQL database using Python with a focus on student registration. We'll cover all CRUD operations (Create, Read, Update, Delete), SQL queries, and how to use Python’s cursor object for efficient database interaction.</p>
        <h2>1. Setting Up the Student Registration Database</h2>
        <p>Let’s assume we have a MySQL database for managing student registration. We will use a table called <code>students</code> with the following structure:</p>
        <pre><code>CREATE TABLE new_students (
    student_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    age INT,
    registration_date DATE
);</code></pre>
        <p>This table stores information about students such as their ID, name, email, age, and the registration date.</p>
        <h2>2. Basic CRUD Operations with Python</h2>
        <h3>2.1 Create (INSERT)</h3>
        <pre><code>import mysql.connector
# Establishing a connection to the MySQL database
connection = mysql.connector.connect(
    host="localhost",
    user="your_username",
    password="your_password",
    database="your_database"
)

# Creating a cursor object
cursor = connection.cursor()

# SQL Insert Query
insert_query = """
    INSERT INTO students (name, email, age, registration_date)
    VALUES (%s, %s, %s, CURDATE())
"""
student_data = ("John Doe", "john@example.com", 20)

# Executing the query
cursor.execute(insert_query, student_data)

# Commit the transaction
connection.commit()

print(f"Student {student_data[0]} added successfully!")

# Closing the connection
cursor.close()
connection.close()
</code></pre>
        <h3>2.2 Read (SELECT)</h3>
        <pre><code>import mysql.connector
# Establishing a connection
connection = mysql.connector.connect(
    host="localhost",
    user="your_username",
    password="your_password",
    database="your_database"
)

cursor = connection.cursor()

# SQL Select Query
select_query = "SELECT * FROM students WHERE age >= %s"
age_filter = (18,)

# Executing the query
cursor.execute(select_query, age_filter)

# Fetching all results
students = cursor.fetchall()

for student in students:
    print(student)

cursor.close()
connection.close()
</code></pre>
        <h3>2.3 Update</h3>
        <pre><code>import mysql.connector
connection = mysql.connector.connect(
    host="localhost",
    user="your_username",
    password="your_password",
    database="your_database"
)

cursor = connection.cursor()

# SQL Update Query
update_query = "UPDATE students SET email = %s WHERE student_id = %s"
updated_data = ("new_email@example.com", 1)

# Executing the query
cursor.execute(update_query, updated_data)

# Commit the transaction
connection.commit()

print("Student email updated successfully!")

cursor.close()
connection.close()
</code></pre>
        <h3>2.4 Delete</h3>
        <pre><code>import mysql.connector
connection = mysql.connector.connect(
    host="localhost",
    user="your_username",
    password="your_password",
    database="your_database"
)

cursor = connection.cursor()

# SQL Delete Query
delete_query = "DELETE FROM students WHERE student_id = %s"
student_id = (1,)

# Executing the query
cursor.execute(delete_query, student_id)

# Commit the transaction
connection.commit()

print("Student deleted successfully!")

cursor.close()
connection.close()
</code></pre>
        <h2>3. Using Cursor Objects for Database Operations</h2>
        <h3>What?</h3>
        <p>A <code>Cursor</code> object in Python is used to execute SQL queries and fetch results from the database.</p>
        <h3>Why?</h3>
        <p>The cursor is essential for handling database operations, such as executing queries and retrieving results. It serves as a bridge between the Python program and the database.</p>
        <h3>How it Works</h3>
        <p>We create a cursor using the <code>connection.cursor()</code> method and execute queries using the cursor object. Once queries are executed, the cursor is used to fetch results, and it is closed after the operations are done. Here's an example:</p>
        <pre><code>cursor = connection.cursor()

# Example: Executing a query
cursor.execute("SELECT * FROM students")

# Fetching results
students = cursor.fetchall()

# Closing the cursor
cursor.close()
</code></pre>
        <h2>4. Executing Multiple Queries in a Single Connection</h2>
        <p>In practice, you may need to execute multiple queries in a single connection. Here’s how to handle it:</p>
        <pre><code>import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="your_username",
    password="your_password",
    database="your_database"
)

cursor = connection.cursor()

# Multiple queries
cursor.execute("INSERT INTO students (name, email, age, registration_date) VALUES ('Jane Doe', 'jane@example.com', 22, CURDATE())")
cursor.execute("UPDATE students SET age = age + 1 WHERE name = 'Jane Doe'")

# Commit the transactions
connection.commit()

cursor.close()
connection.close()
</code></pre>
        <h2>Conclusion</h2>
        <p>Using Python and MySQL together allows you to perform various database operations efficiently. By mastering CRUD operations, SQL queries, and the use of cursor objects, you can manage any relational database easily within Python applications.</p>
<div>

In [25]:
import os
import mysql.connector

# Set an environment variable
os.environ["DB"] = "localhost;root;Avinash@123;python_workshop"
# # from dotenv import load_dotenv

# load_dotenv()  # Load environment variables from .env file

db_details = os.getenv('DB').split(";")
db_host = db_details[0]
db_user = db_details[1]
db_password = db_details[2]
db_name = db_details[3]

connection = mysql.connector.connect(
    host=db_host,
    user=db_user,
    password=db_password,
    database=db_name
)

In [23]:
# creating the cursor object
cursor = connection.cursor()

# make the query string
insert_query = """
    INSERT INTO new_students (name, email, age, registration_date)
    VALUES (%s, %s, %s, CURDATE())
"""
student_data = ("John Doe", "john@example.com", 20)

# excute the query
cursor.execute(insert_query, student_data)

# commit the transection
connection.commit()
print(f"Student {student_data[0]} added successfully!")

# close the connection
if connection.is_connected():
    cursor.close()
    connection.close()
    print("Connection closed successfully!")

Student John Doe added successfully!
Connection closed successfully!

In [26]:
# creating the cursor object
cursor = connection.cursor()

name =  input('Enter student name')
email = input('enter email id')
age = int(input('enter age'))

# make the query string
insert_query = """
    INSERT INTO new_students (name, email, age, registration_date)
    VALUES (%s, %s, %s, CURDATE())
"""

student_data = (name, email, age)

# excute the query
cursor.execute(insert_query, student_data)

# commit the transection
connection.commit()
print(f"Student {student_data[0]} added successfully!")

Enter student name naveen
enter email id naveen@yahoo.com
enter age 24

Student naveen added successfully!

In [27]:
# Query with database table

# creating the cursor object
cursor = connection.cursor()

# query string
select_query = "SELECT * FROM new_students WHERE age >= %s"
age_filter = (18,)

# execute query
cursor.execute(select_query, age_filter)

# Fetching all results

students = cursor.fetchall()

for student in students:
    print(student[1])

John Doe
John Doe
avinash
Vijay
John Doe
naveen

In [31]:
from IPython.core.display import HTML
# Initialize the HTML string for the table
table_html = '<table border="1"><tr>'

# Define the headers and rows for the table
headers = ['ID', 'Name', 'Email', 'Age', 'Registration Date']

# Add headers to the table
for header in headers:
    table_html += f'<th>{header}</th>'
table_html += '</tr>'

# creating the cursor object
cursor = connection.cursor()

# query string
select_query = "SELECT * FROM new_students WHERE age >= %s"
age_filter = (18,)

# execute query
cursor.execute(select_query, age_filter)

# Fetching all results

students = cursor.fetchall()
    
# Add rows to the table
for student in students:
    table_html += '<tr>'
    for cell in student:
        table_html += f'<td>{cell}</td>'
    table_html += '</tr>'

# Close the table
table_html += '</table>'

# Display the table using IPython display
display(HTML(table_html))

In [29]:
# create the cursor object
cursor = connection.cursor()

# SQL Update Query
name = input('enter the name')
email = input('enter the new mail id')

update_query = "UPDATE new_students SET email = %s WHERE name = %s"
updated_data = (email, name)

#Executing the query

cursor.execute(update_query, updated_data)

#Commit the transaction

connection.commit()

print("Student email updated successfully!")

enter the name avinash
enter the new mail id avinash@gmail.com

Student email updated successfully!

In [30]:
# create cursor object
cursor = connection.cursor()

#SQL Delete Query

id = int(input('Please enter student id')) 
delete_query = "DELETE FROM new_students WHERE student_id = %s"
student_id = (id,)

#Executing the query

cursor.execute(delete_query, student_id)

#Commit the transaction

connection.commit()

print("Student deleted successfully!")

Please enter student id 1

Student deleted successfully!

In [ ]:
# close the connection
if connection.is_connected():
    cursor.close()
    connection.close()
    print("Connection closed successfully!")